name: azyx
description: "AzyX"
publish_to: "none"
version: 2.6.4-beta+3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get:
  provider:
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  dynamic_color: ^1.7.0
  html: ^0.15.0
  url_launcher: ^6.3.0
  http: ^1.2.2
  device_info_plus: any
  permission_handler: any
  # flutter_local_notifications: any
  dio: ^5.7.0
  media_kit: ^1.2.0
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.6
  wakelock_plus: ^1.2.8
  flutter_web_auth_2: ^4.0.2
  # sidebarx: ^0.17.1
  # dart_eval: ^0.7.10
  dartotsu_extension_bridge:
    git:
     url: https://github.com/aayush2622/DartotsuExtensionBridge.git
     ref: 239ef59
  # isar_flutter_libs:
  #   git:
  #     url: https://github.com/MrLittleWhite/isar_flutter_libs.git
  #     ref: main
  # http_interceptor: ^2.0.0
  # share_plus: ^10.1.3
  # js_packer: ^0.0.5
  # flutter_riverpod: ^2.6.1
  # riverpod_annotation: ^2.6.1
  # flutter_gen: ^5.8.0
  # go_router: ^14.6.2
  # json_path: ^0.7.4
  # bot_toast: ^4.1.3
  # freezed_annotation: ^2.0.0
  # flutter_rust_bridge: ^2.3.0
  # xpath_selector_html_parser: ^3.0.1
  # flutter_qjs:
  #   git:
  #     url: https://github.com/kodjodevf/flutter_qjs.git
  #     ref: main
  # pseudom: ^1.0.1
  # intl: ^0.18.1
  isar_community: ^3.3.0-dev.3
  isar_community_flutter_libs: ^3.3.0-dev.3
  isar_community_generator: ^3.3.0-dev.3
  icons_plus: ^5.0.0
  grouped_list: ^6.0.0
  volume_controller: ^3.4.0
  screen_brightness: ^2.1.5
  path: ^1.9.0
  # encrypt: ^5.0.3
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.2.1
  checkmark: ^0.0.2+1
  shimmer: ^3.0.0
  ionicons: ^0.2.2
  carousel_slider: ^5.0.0
  # manga_page_view:
  #   git: https://github.com/reyyuuki/manga_page_view
  path_provider: ^2.1.5
  expandable_page_view: ^1.0.17
  manga_page_view: ^1.0.5
  lottie: ^3.3.1
  app_links: ^6.4.1
  flutter_acrylic: ^1.1.4
  bitsdojo_window: ^0.1.6
  readmore: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # hive_generator: ^2.0.1
  # flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.jpg"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/images/icon.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/icon.jpg"
  linux:
    generate: true
    image_path: "assets/images/icon.jpg"


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/sticker.png
    - assets/images/icon.jpg
    - assets/images/
    - assets/animations/
  fonts:
    - family: broken
      fonts:
        - asset: assets/fonts/broken.ttf
    - family: broken_filled
      fonts:
        - asset: assets/fonts/broken_filled.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
# assets:
#   - .env

# fonts:
#   - family: broken
#     fonts:
#       - asset: assets/fonts/broken.ttf
#   - family: broken_filled
#     fonts:
#       - asset: assets/fonts/broken_filled.ttf
#   - family: Poppins
#     fonts:
#       - asset: assets/fonts/Poppins/Poppins-Regular.ttf
#   - family: Poppins-Bold
#     fonts:
#       - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
