name: azyx
description: "A new Flutter project."
publish_to: 'none'
version: 2.6.2

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  iconsax: ^0.0.8
  infinite_carousel: ^1.1.1
  ionicons: ^0.2.2
  text_scroll: ^0.2.0
  lite_rolling_switch: ^1.0.1
  cached_network_image: ^3.4.1
  provider:
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  dynamic_color: ^1.7.0
  flutter_launcher_icons: ^0.13.1
  html: ^0.15.0
  url_launcher: ^6.3.0
  flutter_dotenv: ^5.1.0
  animated_segmented_tab_control: ^2.0.0
  encrypt: ^5.0.3
  google_fonts: ^6.2.1
  device_info_plus: any
  permission_handler: any
  flutter_local_notifications: any
  dio: ^5.7.0
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  wakelock_plus: ^1.2.8
  flutter_web_auth_2: ^4.0.2
  sidebarx: ^0.17.1
  dart_eval: ^0.7.10
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  http_interceptor: ^2.0.0
  share_plus: ^10.1.3
  js_packer: ^0.0.5
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_gen: ^5.8.0
  go_router: ^14.6.2
  json_path: ^0.7.4
  bot_toast: ^4.1.3
  freezed_annotation: ^2.0.0
  flutter_rust_bridge: ^2.3.0
  xpath_selector_html_parser: ^3.0.1
  flutter_qjs:
    git:
      url: https://github.com/kodjodevf/flutter_qjs.git
      ref: main
  pseudom: ^1.0.1
  intl: ^0.18.1
  icons_plus: ^5.0.0
  grouped_list: ^6.0.0
  volume_controller: ^2.0.8
  screen_brightness: ^0.2.2+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"
  

flutter:
  uses-material-design: true

  assets:
  - .env
  - assets/icon/icon.png
  fonts:
    - family: broken
      fonts:
        - asset: assets/fonts/broken.ttf
    - family: broken_filled
      fonts:
        - asset: assets/fonts/broken_filled.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        # Add other styles (italic, bold, etc.) if available
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        # - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        # - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        # - asset: assets/fonts/Poppins/Poppins-Medium.ttf


